export const userData = {
  name: "Devesh",
  title: "Full Stack Developer",
  tagline: "Crafting digital experiences from the ground up",
  bio: "Passionate full stack developer with expertise in building scalable web applications. I love turning complex problems into elegant, user-friendly solutions. Always exploring new technologies and pushing the boundaries of what's possible on the web.",
  profileImage: "/images/profile.jpg",
  highlights: [
    { label: "Years Experience", value: "3+" },
    { label: "Projects Delivered", value: "20+" },
    { label: "Technologies", value: "15+" },
    { label: "Contributions", value: "50+" },
  ],
  services: [
    {
      id: "1",
      icon: "🌐",
      title: "Web Development",
      description: "Building responsive, high-performance web applications using modern frameworks and best practices.",
    },
    {
      id: "2",
      icon: "📱",
      title: "Mobile Development",
      description: "Creating cross-platform mobile apps with React Native that feel native on every device.",
    },
    {
      id: "3",
      icon: "⚡",
      title: "API & Backend",
      description: "Designing RESTful and GraphQL APIs with Node.js, handling complex business logic efficiently.",
    },
    {
      id: "4",
      icon: "🎨",
      title: "UI/UX Design",
      description: "Crafting intuitive, beautiful interfaces that prioritize user experience and accessibility.",
    },
    {
      id: "5",
      icon: "☁️",
      title: "Cloud & DevOps",
      description: "Deploying and managing applications on AWS, GCP with CI/CD pipelines.",
    },
    {
      id: "6",
      icon: "🔒",
      title: "Security",
      description: "Implementing security best practices including authentication, authorization, and data encryption.",
    },
  ],
  experience: [
    {
      id: "1",
      role: "Senior Full Stack Developer",
      company: "Tech Solutions Inc.",
      duration: "2023 - Present",
      description: "Leading development of enterprise-grade web applications using React, Node.js, and AWS. Mentoring junior developers and architecting scalable solutions.",
      technologies: ["React", "Node.js", "AWS", "PostgreSQL", "Docker"],
    },
    {
      id: "2",
      role: "Full Stack Developer",
      company: "Digital Agency Co.",
      duration: "2022 - 2023",
      description: "Developed and maintained multiple client projects. Implemented responsive designs and RESTful APIs. Collaborated with design teams to deliver pixel-perfect UIs.",
      technologies: ["Next.js", "Express", "MongoDB", "Tailwind CSS"],
    },
    {
      id: "3",
      role: "Frontend Developer",
      company: "StartupXYZ",
      duration: "2021 - 2022",
      description: "Built the front-end architecture from scratch for a SaaS platform. Improved performance by 40% through code splitting and lazy loading.",
      technologies: ["React", "TypeScript", "Redux", "GraphQL"],
    },
  ],
  skills: {
    Frontend: ["React", "Next.js", "TypeScript", "Tamagui", "Framer Motion", "CSS/SCSS"],
    Backend: ["Node.js", "Express", "GraphQL", "REST APIs", "Python", "PostgreSQL"],
    Tools: ["Git", "Docker", "AWS", "Figma", "VS Code", "GitHub Actions"],
  },
  projects: [
    {
      id: "1",
      title: "E-Commerce Platform",
      description: "A full-featured e-commerce platform with real-time inventory management, payment processing, and an admin dashboard.",
      techStack: ["Next.js", "Node.js", "Stripe", "PostgreSQL", "Redis"],
      liveLink: "https://example.com",
      demoLink: "https://github.com",
      featured: true,
    },
    {
      id: "2",
      title: "Task Management App",
      description: "A collaborative task management application with real-time updates, drag-and-drop interface, and team collaboration features.",
      techStack: ["React", "Socket.io", "Express", "MongoDB"],
      liveLink: "https://example.com",
      demoLink: "https://github.com",
      featured: true,
    },
    {
      id: "3",
      title: "AI Content Generator",
      description: "An AI-powered content generation tool that creates blog posts, social media content, and marketing copy using GPT API.",
      techStack: ["Next.js", "OpenAI API", "Prisma", "PostgreSQL"],
      liveLink: "https://example.com",
      demoLink: "https://github.com",
      featured: false,
    },
    {
      id: "4",
      title: "Real-time Analytics Dashboard",
      description: "Interactive analytics dashboard with real-time data visualization, custom reports, and alerts system.",
      techStack: ["React", "D3.js", "WebSocket", "Node.js", "InfluxDB"],
      liveLink: "https://example.com",
      demoLink: "https://github.com",
      featured: false,
    },
  ],
  contact: {
    email: "devesh@example.com",
    github: "devesh04-sec",
    linkedin: "devesh",
    twitter: "",
  },
}
